FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["celery", "-A", "ai.app.workers.celery_app.celery_app", "worker", "-Q", "celery", "--loglevel=info"]
